### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by mnesarco** [bernhard-42/ocp-tessellate#4]
Thank you for all your libs around ocp. 
Please add a license file to make it explicit. I see that some of your python files have an Apache-2.0 License header.

**Comment by bernhard-42** [comment]
very good point, thanks. It was always a "helper" module and hence I completely forgot that.
I have a new release in a few days ready which will have an Apache 2.0 license file

**Comment by mnesarco** [comment]
Excellent! I am planning to use this tessellator in a scene graph widget i am working on based on Qt3D/Qrhi, so it should be portable across GL,Vulkan,Metal,DirextX,...
