### ISSUE TITLE
3.0.8 not in repo

### ISSUE THREAD

**Issue by erooke** [bernhard-42/ocp-tessellate#7]
`pyproject.toml` still claims the version is 3.0.7 despite the version being 3.0.8.

edit:
Upon further inspection it looks like the code in the repository may not be version 3.0.8 despite being tagged as such? Its missing the method `get_surface` and in general does not line up to the tar archive attached to the [github release](https://github.com/bernhard-42/ocp-tessellate/releases/tag/v3.0.8).

**Comment by bernhard-42** [comment]
Thanks, I forgot to push the changes this time.
But now everything is up to date.

**Comment by erooke** [comment]
Thanks!
